# Dependencies
markdown:       kramdown
extensions:     [strikethrough,smart,with_toc_data]
highlighter:    rouge

# Permalinks
permalink:        /posts/:title/

# User Configuration
title:            Jekyll Starter
tagline:          'A starter project for Jekyll'
description:      'Engineer'
url:              https://ksivam.github.io/
baseurl:          '/'
paginate:         3
excerpt_separator: '<br>'
gems:
- jekyll-paginate
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

# Author Info
author:
  name:           'Krishna Sadasivam'
  url:            https://ksivam.github.io/

# Social Integration
social:
  twitter:        ksadasivam
  disqus:         ksivam-github-io
  addthis_pubid:  ra-587bffea6c68282b

# Google Analytics Configuration
# Proxy response must be in JSON and should have the fields - ga:pagePath, ga:pageview
google_analytics:
  tracking_id:      UA-90420739-1
  super_proxy_url:  

# Github
github:
  repo:           https://github.com/ksivam/ksivam.github.io
  feedback:       https://github.com/ksivam/ksivam.github.io/issues

# Version Info
version:          0.0.0
