# Dependencies
markdown:         redcarpet
redcarpet:
  extensions:     [strikethrough,smart,with_toc_data]
highlighter:      pygments

# Permalinks
permalink:        /posts/:title/

# User Configuration
title:            =testtr
tagline:          'ee'
description:      'ee'
url:              ee
baseurl:          '/'
paginate:         3
excerpt_separator: '<br>'
gems:
- jekyll-paginate
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

# Author Info
author:
  name:           'Me'
  url:            ee

# Social Integration
social:
  twitter:        
  disqus:         
  addthis_pubid:  

# Google Analytics Configuration
# Proxy response must be in JSON and should have the fields - ga:pagePath, ga:pageview
google_analytics:
  tracking_id:      
  super_proxy_url:  

# Github
github:
  repo:           
  feedback:       

# Version Info
version:          0.0.0
